name: "Bug Report"
description: "File a bug report with detailed reproduction steps"
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Short title summarizing the bug
      placeholder: ex. "App crashes on clicking Save"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: A step-by-step guide to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what really happened.
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgently does this need to be resolved?
      options:
        - Low
        - Medium
        - High
      default: 1  # Medium
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the impact of this bug?
      options:
        - Critical
        - High
        - Medium
        - Low
      default: 2  # Medium
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or screen recordings
      description: You can paste images directly into this field or upload them using the UI.
      placeholder: Paste or upload screenshots here (if available)
    validations:
      required: false
